{
 "title": "Arpeg trader",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Spotřeba",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Consumption{part=\"Total\"}",
     "legendFormat": "__auto"
    },
    { "expression": "B", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Výroba",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Feed{part=\"Total\"}",
     "legendFormat": "__auto"
    },
    { "expression": "B", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Grid statistika",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "Nakup", "reducer": "sum", "settings": { "mode": "replaceNN", "replaceWithValue": 0 }, "type": "reduce" },
    { "expression": "Prodej", "reducer": "sum", "settings": { "mode": "replaceNN", "replaceWithValue": 0 }, "type": "reduce" }
   ]
  },
  {
   "title": "Pokryto spotřeby",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(Feed{part=\"Total\"}[1m])/avg_over_time(Consumption{part=\"Total\"}[1m]) * 100",
     "legendFormat": "__auto"
    },
    { "expression": "$InvSum/$ConsumeSum * 100", "type": "math" }
   ]
  },
  {
   "title": "Baterie",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Battery{part=~\"SOC\"}",
     "legendFormat": "Nabito"
    }
   ]
  },
  {
   "title": "Stringy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PV{part=\"PV1_Voltage\"} / 10",
     "legendFormat": "PV1"
    },
    {
     "expr": "PV{part=\"PV1_Voltage\"} / 10",
     "legendFormat": "PV2"
    },
    {
     "expr": "PV{part=\"PV1_Wats\"}",
     "legendFormat": "PV1"
    },
    {
     "expr": "PV{part=\"PV2_Wats\"}",
     "legendFormat": "PV2"
    }
   ]
  },
  {
   "title": "PV Dodaná energie",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "PV1", "reducer": "sum", "settings": { "mode": "replaceNN", "replaceWithValue": 0 }, "type": "reduce" },
    { "expression": "PV2", "reducer": "sum", "settings": { "mode": "replaceNN", "replaceWithValue": 0 }, "type": "reduce" }
   ]
  },
  {
   "title": "Grid",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Grid{part=\"Total\"}",
     "legendFormat": "Grid W"
    }
   ]
  },
  {
   "title": "Napětí baterie",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Battery{part=\"V\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Teploty",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "Temperature{part=\"Temperature_Air\"} / 10 < 110",
     "legendFormat": "Modul"
    },
    {
     "expr": "Temperature{part=\"Temperature_Radiator\"} / 10 < 110",
     "legendFormat": "Chladič"
    }
   ]
  },
  {
   "title": "L1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "Grid{part=\"L1\"}",
     "legendFormat": "Grid"
    },
    {
     "expr": "Feed{part=\"L1\"}",
     "legendFormat": "Inv"
    },
    {
     "expr": "Consumption{part=\"L1\"}",
     "legendFormat": "Dům"
    }
   ]
  },
  {
   "title": "Max příkon",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "downsampler": "mean",
     "expression": "L1Source",
     "reducer": "max",
     "settings": { "mode": "dropNN" },
     "type": "reduce",
     "upsampler": "fillna"
    },
    { "expression": "L2Source", "reducer": "max", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "L3Source", "reducer": "max", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Celkem",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "Grid{part=\"Total\"}",
     "legendFormat": "Export/Import"
    },
    {
     "expr": "Feed{part=\"Total\"}",
     "legendFormat": "Výroba"
    },
    {
     "expr": "Export{part=\"Limit\"}",
     "legendFormat": "ExportLimit"
    },
    {
     "expr": "Battery{part=\"W\"}",
     "legendFormat": "Baterie"
    }
   ]
  },
  {
   "title": "L2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "Grid{part=\"L1\"}",
     "legendFormat": "Grid"
    },
    {
     "expr": "Feed{part=\"L2\"}",
     "legendFormat": "Inv"
    },
    {
     "expr": "Consumption{part=\"L2\"}",
     "legendFormat": "Dům"
    }
   ]
  },
  {
   "title": "L3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "Grid{part=\"L3\"}",
     "legendFormat": "Grid"
    },
    {
     "expr": "Feed{part=\"L3\"}",
     "legendFormat": "Inv"
    },
    {
     "expr": "Consumption{part=\"L3\"}",
     "legendFormat": "Dům"
    }
   ]
  },
  {
   "title": "Spotřeba",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "Consumption{part=\"L1\"}",
     "legendFormat": "L1"
    },
    {
     "expr": "Consumption{part=\"L2\"}",
     "legendFormat": "L2"
    },
    {
     "expr": "Consumption{part=\"L3\"}",
     "legendFormat": "L3"
    },
    {
     "expr": "Consumption{part=\"Total\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Baterie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "Battery{part=~\"SOC|MinSOC\"}",
     "legendFormat": "{{part}}"
    },
    {
     "expr": "Battery{part=~\"Mode\"}*10",
     "legendFormat": "{{part}}"
    }
   ]
  },
  {
   "title": "Cena vs Předpověď osvitu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expr": "PV_forecast", "legendFormat": "Předpověď" },
    { "expr": "Price", "legendFormat": "Cena Eur" }
   ]
  }
 ]
}