name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      tagversion: ${{ $(date +%s) }}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2.1.0
      with:
        username: marekiss
        password: 11121988
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag marekiss/arpeg_trader:$tagversion
    - name: add tag latest
      run: docker tag marekiss/arpeg_trader:$tagversion marekiss/arpeg_trader:latest
    - name: Publish docker image
      run: docker push marekiss/arpeg_trader:$tagversion
